- name: Check environment
  env:
    PROGRAMMERS_TOKEN_ID: ${{ secrets.PROGRAMMERS_TOKEN_ID }}
    PROGRAMMERS_TOKEN_PW: ${{ secrets.PROGRAMMERS_TOKEN_PW }}
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    test -n "$PROGRAMMERS_TOKEN_ID" && echo "PROGRAMMERS_TOKEN_ID is set"
    test -n "$PROGRAMMERS_TOKEN_PW" && echo "PROGRAMMERS_TOKEN_PW is set"
    test -n "$GH_PAT" && echo "GH_PAT is set"
